[package]
name = "simple-text-editor"
version = "0.2.0"
authors = ["Steve Manuel <nilslice@gmail.com>"]
edition = "2018"
description = "Basic implementation of a simple text editor, as a Rust library and CLI."
license = "BSD-3-Clause"

[dependencies]
